name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "1.13.1"
          elixir-version: "25.3"
          version-type: strict

      - uses: actions/cache@v3
        with:
          path: umbrella1/_build
          key: mix-build

      - run: |
          cd umbrella1 && mix compile --verbose
