name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.13.4"
              otp: "25.3"
          - pair:
              elixir: "1.14.4"
              otp: "25.3"
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
          version-type: strict

      - uses: actions/cache@v3
        with:
          path: _build
          key: mix-build-${{ matrix.pair.elixir }}-${{ matrix.pair.otp }}

      - run: |
          mix compile --verbose
